# AI Dev dataset

In [ ]:
import pandas as pd
all_pr_df = pd.read_parquet("hf://datasets/hao-li/AIDev/all_pull_request.parquet")
all_repo_df = pd.read_parquet("hf://datasets/hao-li/AIDev/all_repository.parquet")
all_user_df = pd.read_parquet("hf://datasets/hao-li/AIDev/all_user.parquet")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
all_pr_df

,id,number,title,body,agent,user_id,user,state,created_at,closed_at,merged_at,repo_id,repo_url,html_url
0,3264016139,1688,`metta code` --> `metta clip` and additional p...,Remove unused `root_key` variable to fix ruff ...,Claude_Code,37011,jacklionheart,closed,2025-07-25T18:15:36Z,2025-07-25T19:17:23Z,2025-07-25T19:17:23Z,8.439884e+08,https://api.github.com/repos/Metta-AI/metta,https://github.com/Metta-AI/metta/pull/1688
1,3264021033,41,feat: Comprehensive ruff error resolution with...,## 🎯 Mission Accomplished: 100% Ruff Error Res...,Claude_Code,131842369,Draco3310,open,2025-07-25T18:17:57Z,None,None,9.920635e+08,https://api.github.com/repos/Draco3310/Gal-Fri...,https://github.com/Draco3310/Gal-Friday2/pull/41
2,3264042289,1600,Add Evals frontend implementation plan and HTM...,\nCreate comprehensive implementation plan for...,Claude_Code,6766889,justicart,closed,2025-07-25T18:26:15Z,2025-07-25T23:19:14Z,None,9.267118e+08,https://api.github.com/repos/bolt-foundry/bolt...,https://github.com/bolt-foundry/bolt-foundry/p...
3,3264042318,1601,Add 4 new BfDs components for Evals interface ...,\nPhase 1 component creation for the Evals fro...,Claude_Code,6766889,justicart,closed,2025-07-25T18:26:16Z,2025-07-25T23:19:11Z,None,9.267118e+08,https://api.github.com/repos/bolt-foundry/bolt...,https://github.com/bolt-foundry/bolt-foundry/p...
4,3264067496,3,🚀 Complete Frontend-Backend API Integration wi...,## 🎯 Summary\n\nThis PR completes the **fronte...,Claude_Code,42357482,twitchyvr,closed,2025-07-25T18:39:14Z,2025-07-25T18:48:47Z,2025-07-25T18:48:47Z,1.025871e+09,https://api.github.com/repos/twitchyvr/Spaghetti,https://github.com/twitchyvr/Spaghetti/pull/3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932786,2858495710,79,chore: update RPC endpoint and build target,# Update RPC Endpoint and Build Target\n\nUpda...,Devin,158243242,devin-ai-integration[bot],closed,2025-02-17T17:53:32Z,2025-02-17T17:54:19Z,2025-02-17T17:54:19Z,9.274854e+08,https://api.github.com/repos/xiayuhkust/TuraWAP,https://github.com/xiayuhkust/TuraWAP/pull/79
932787,2858498986,6,feat: enhance recruitment management system wi...,# Enhanced Recruitment Management System\n\nTh...,Devin,158243242,devin-ai-integration[bot],closed,2025-02-17T17:55:34Z,2025-02-18T02:19:26Z,2025-02-18T02:19:26Z,9.334548e+08,https://api.github.com/repos/crb12546/musical-...,https://github.com/crb12546/musical-memory/pull/6
932788,2858525953,80,fix: revert to PR #73 OpenAI config with updat...,# Revert to PR #73 with Updated RPC Endpoint\n...,Devin,158243242,devin-ai-integration[bot],closed,2025-02-17T18:10:27Z,2025-02-17T18:13:05Z,2025-02-17T18:13:05Z,9.274854e+08,https://api.github.com/repos/xiayuhkust/TuraWAP,https://github.com/xiayuhkust/TuraWAP/pull/80
932789,2858527610,400,Add Doxygen Documentation for Public APIs,# Add Doxygen Documentation for Public APIs\n\...,Devin,158243242,devin-ai-integration[bot],closed,2025-02-17T18:11:27Z,2025-02-22T01:15:27Z,None,1.195796e+08,https://api.github.com/repos/wolfSSL/wolfTPM,https://github.com/wolfSSL/wolfTPM/pull/400
932790,2858539698,2,Convert remaining JavaScript files to ES modules,# Convert remaining JavaScript files to ES mod...,Devin,158243242,devin-ai-integration[bot],closed,2025-02-17T18:18:45Z,2025-02-18T00:30:37Z,2025-02-18T00:30:37Z,9.339834e+08,https://api.github.com/repos/shixin-guo/boostr,https://github.com/shixin-guo/boostr/pull/2

In [ ]:
all_repo_df

,id,url,license,full_name,language,forks,stars
0,987641962,https://api.github.com/repos/1010-dev/senjudev...,None,1010-dev/senjudev-site,TypeScript,1.0,0.0
1,990249393,https://api.github.com/repos/106-/HellSinkerWa...,None,106-/HellSinkerWallPaper,Java,0.0,0.0
2,1009549206,https://api.github.com/repos/1genadam/tileshop...,None,1genadam/tileshop-rag,Python,0.0,0.0
3,983546765,https://api.github.com/repos/1kimnet/ETL-pipeline,None,1kimnet/ETL-pipeline,Python,0.0,0.0
4,1024190983,https://api.github.com/repos/20m61/lightningta...,None,20m61/lightningtalk-circle,JavaScript,0.0,0.0
...,...,...,...,...,...,...,...
116206,1020305485,https://api.github.com/repos/zx8086/kong-konne...,None,zx8086/kong-konnect-app,Svelte,0.0,0.0
116207,976509925,https://api.github.com/repos/zx8086/mcp-server...,None,zx8086/mcp-server-couchbase,TypeScript,0.0,0.0
116208,989288917,https://api.github.com/repos/zx8086/mcp-server...,Apache-2.0,zx8086/mcp-server-elasticsearch,TypeScript,0.0,0.0
116209,915873255,https://api.github.com/repos/zxcpluto/First,None,zxcpluto/First,None,0.0,0.0
116210,1000819309,https://api.github.com/repos/zyumax/devin-hand...,None,zyumax/devin-hands-on,JavaScript,0.0,0.0

In [ ]:
all_user_df

                id          login  followers  following            created_at
0      149159513.0     00012122Cs        0.0        0.0  2023-10-27T10:22:50Z
1       86906973.0     000Sean000        0.0        2.0  2021-07-04T07:05:40Z
2       36679210.0        000alen       46.0      106.0  2018-02-20T21:00:55Z
3      201261210.0       000qhrey        0.0        1.0  2025-02-28T16:53:21Z
4       22735204.0       00125495        0.0        1.0  2016-10-10T01:24:34Z
...            ...            ...        ...        ...                   ...
72184  128873850.0       zztime04        0.0        1.0  2023-03-25T01:50:00Z
72185   46803451.0  zzy1099207684        0.0        1.0  2019-01-18T02:51:48Z
72186   35818234.0      zzzpotato        2.0        0.0  2018-01-25T20:59:53Z
72187   55004427.0        zzzsaft        1.0        0.0  2019-09-06T21:50:29Z
72188   46273764.0        zzzz465       42.0       71.0  2018-12-31T04:08:21Z

[72189 rows x 5 columns]

In [ ]:
# Only list users having more than 100 follows in all_user_df
all_user_more_100_df = all_user_df[all_user_df['following'] > 100].sort_values(by='following', ascending=False)
all_user_more_100_df

,id,login,followers,following,created_at
55766,6391776.0,nikitavoloboev,4857.0,16742.0,2014-01-13T17:30:13Z
25343,102006756.0,ZigaoWang,1340.0,15140.0,2022-03-21T03:01:30Z
57236,12672027.0,owenlamont,351.0,13886.0,2015-05-30T11:51:27Z
11346,178424.0,JeffCarpenter,369.0,11633.0,2010-01-08T08:54:08Z
53170,1325144.0,mikedemarais,1741.0,9583.0,2012-01-12T16:05:15Z
...,...,...,...,...,...
36843,1858708.0,drugoi,86.0,101.0,2012-06-17T11:08:34Z
59463,17099856.0,rafaelrojasmiliani,35.0,101.0,2016-02-06T16:54:25Z
68728,6257997.0,vdubya,23.0,101.0,2013-12-25T07:38:04Z
70680,1251311.0,xywei,46.0,101.0,2011-12-09T03:08:04Z
72150,97125186.0,zyang91,6.0,101.0,2022-01-04T19:14:25Z

In [ ]:
# only list pr committed by OpenAI_Codex
all_pr_by_codex_df = all_pr_df[all_pr_df['agent'] == 'OpenAI_Codex']
all_pr_by_codex_df.head(10)

,id,number,title,body,agent,user_id,user,state,created_at,closed_at,merged_at,repo_id,repo_url,html_url
55584,3122393615,45,Improve FICA estimate helpers,## Summary\n- refine FICA helper functions\n- ...,OpenAI_Codex,130411308,mattb3113,closed,2025-06-05T19:28:33Z,2025-06-05T19:29:00Z,2025-06-05T19:29:00Z,996823776.0,https://api.github.com/repos/mattb3113/docs,https://github.com/mattb3113/docs/pull/45
55585,3122395724,55,Add message deletion and read receipts,## Summary\r\n- refine chat UI with read recei...,OpenAI_Codex,84555510,AusBoone,closed,2025-06-05T19:29:23Z,2025-06-05T19:29:45Z,2025-06-05T19:29:44Z,633640641.0,https://api.github.com/repos/AusBoone/PrivateLine,https://github.com/AusBoone/PrivateLine/pull/55
55586,3122408581,20,Fix cdscli to persist CDS and zone updates,## Summary\n- write CDS files and update zones...,OpenAI_Codex,23141173,jgwill,closed,2025-06-05T19:33:22Z,2025-06-05T20:17:57Z,2025-06-05T20:17:57Z,569242530.0,https://api.github.com/repos/jgwill/jgtpy,https://github.com/jgwill/jgtpy/pull/20
55587,3122417785,79,Use shared RabbitMQ client,## Summary\n- expose RabbitMQ service from sha...,OpenAI_Codex,88899913,Mohammedareebali,closed,2025-06-05T19:36:58Z,2025-06-05T19:37:28Z,2025-06-05T19:37:28Z,996361900.0,https://api.github.com/repos/Mohammedareebali/...,https://github.com/Mohammedareebali/send/pull/79
55588,3122418753,125,Split large css file,## Summary\n- divide the huge `style.css` into...,OpenAI_Codex,98446918,rdwr-taly,closed,2025-06-05T19:37:20Z,2025-06-05T19:37:42Z,2025-06-05T19:37:42Z,983675963.0,https://api.github.com/repos/Radware/radware-v...,https://github.com/Radware/radware-vulnerable-...
55589,3122420688,24,Fix duplicate tower removal function,## Summary\n- remove redundant `removeIncorrec...,OpenAI_Codex,5239796,yannage,closed,2025-06-05T19:38:07Z,2025-06-05T19:39:21Z,2025-06-05T19:39:21Z,954628547.0,https://api.github.com/repos/yannage/Sudoku-De...,https://github.com/yannage/Sudoku-Defense/pull/24
55590,3122424442,36,Improve interval cleanup in App,## Summary\n- manage interval ID via `useRef`\...,OpenAI_Codex,130038870,jasonlryan,closed,2025-06-05T19:39:25Z,2025-06-05T20:54:41Z,2025-06-05T20:54:41Z,991966565.0,https://api.github.com/repos/jasonlryan/hyatt-...,https://github.com/jasonlryan/hyatt-demo/pull/36
55591,3122425258,25,Fix flutter analyze issues,## Summary\n- prefer final for unchanging fiel...,OpenAI_Codex,214921637,ClubBoss,closed,2025-06-05T19:39:50Z,2025-06-05T19:40:00Z,2025-06-05T19:40:00Z,996455123.0,https://api.github.com/repos/ClubBoss/Poker_An...,https://github.com/ClubBoss/Poker_Analyzer/pul...
55592,3122426013,113,Fix EMG overflow with scipy PDF,## Summary\n- improve stability of `emg_left` ...,OpenAI_Codex,43553722,keeganpaleshi,closed,2025-06-05T19:40:05Z,2025-06-05T19:45:05Z,2025-06-05T19:45:05Z,995736506.0,https://api.github.com/repos/keeganpaleshi/RMTest,https://github.com/keeganpaleshi/RMTest/pull/113
55593,3122430562,5,Clean up duplicate files,## Summary\n- remove extraneous spreadsheet fi...,OpenAI_Codex,82644920,prabalkaushik,closed,2025-06-05T19:41:49Z,2025-06-05T19:42:16Z,2025-06-05T19:42:16Z,659416692.0,https://api.github.com/repos/prabalkaushik/Sen...,https://github.com/prabalkaushik/Sentiment-Ana...

# AIDev-pop (more than 100 stars)

In [ ]:
# Basic
pr_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pull_request.parquet")
repo_df = pd.read_parquet("hf://datasets/hao-li/AIDev/repository.parquet")
user_df = pd.read_parquet("hf://datasets/hao-li/AIDev/user.parquet")

# Comments and reviews
pr_comments_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pr_comments.parquet")
pr_reviews_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pr_reviews.parquet")
pr_review_comments_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pr_review_comments_v2.parquet")

# Commits
pr_commits_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pr_commits.parquet")
pr_commit_details_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pr_commit_details.parquet")

# Related issues
related_issue_df = pd.read_parquet("hf://datasets/hao-li/AIDev/related_issue.parquet")
issue_df = pd.read_parquet("hf://datasets/hao-li/AIDev/issue.parquet")

# Events
pr_timeline_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pr_timeline.parquet")

# Task type
pr_task_type_df = pd.read_parquet("hf://datasets/hao-li/AIDev/pr_task_type.parquet")

# Human-PR
human_pr_df = pd.read_parquet("hf://datasets/hao-li/AIDev/human_pull_request.parquet")
human_pr_task_type_df = pd.read_parquet("hf://datasets/hao-li/AIDev/human_pr_task_type.parquet")

In [ ]:
print(f"len(pr_df): {len(pr_df)}")
print(f"len(repo_df): {len(repo_df)}")
print(f"len(user_df): {len(user_df)}")

print(f"len(pr_comments_df): {len(pr_comments_df)}")
print(f"len(pr_reviews_df): {len(pr_reviews_df)}")
print(f"len(pr_review_comments_df): {len(pr_review_comments_df)}")

print(f"len(pr_commits_df): {len(pr_commits_df)}")
print(f"len(pr_commit_details_df): {len(pr_commit_details_df)}")


print(f"len(related_issue_df): {len(related_issue_df)}")
print(f"len(issue_df): {len(issue_df)}")

print(f"len(pr_timeline_df): {len(pr_timeline_df)}")

print(f"len(pr_task_type_df): {len(pr_task_type_df)}")

print(f"len(human_pr_df): {len(human_pr_df)}")
print(f"len(human_pr_task_type_df): {len(human_pr_task_type_df)}")

len(pr_df): 33596
len(repo_df): 2807
len(user_df): 1796
len(pr_comments_df): 39122
len(pr_reviews_df): 28875
len(pr_review_comments_df): 26868
len(pr_commits_df): 88576
len(pr_commit_details_df): 711923
len(related_issue_df): 4923
len(issue_df): 4614
len(pr_timeline_df): 325500
len(pr_task_type_df): 33596
len(human_pr_df): 6618
len(human_pr_task_type_df): 6618

In [ ]:
human_pr_df

,id,number,title,user,user_id,state,created_at,closed_at,merged_at,repo_url,html_url,body,agent
0,2336888723,85268,feat(aci): add automations index page,ameliahsu,55610339,closed,2025-02-14T19:04:59Z,2025-02-18T22:42:20Z,2025-02-18T22:42:19Z,https://api.github.com/repos/getsentry/sentry,https://github.com/getsentry/sentry/pull/85268,https://sentry-j41gpomr5.sentry.dev/automation...,Human
1,2447123365,89131,ref(insights): Make use of `<FeatureBadge>` fo...,ryan953,187460,closed,2025-04-08T23:29:50Z,2025-04-09T15:56:55Z,2025-04-09T15:56:54Z,https://api.github.com/repos/getsentry/sentry,https://github.com/getsentry/sentry/pull/89131,Using the premade component reduces an import ...,Human
2,2438086945,88748,:bug: fix: update how we fetch workflow_id and...,iamrajjoshi,33237075,closed,2025-04-03T21:36:59Z,2025-04-04T15:10:57Z,2025-04-04T15:10:57Z,https://api.github.com/repos/getsentry/sentry,https://github.com/getsentry/sentry/pull/88748,i realized i made a mistake for how i fetch th...,Human
3,2265431531,83085,fix(org-stats): Require project membership,ArthurKnaus,7033940,closed,2025-01-08T07:47:13Z,2025-01-08T08:49:40Z,2025-01-08T08:49:40Z,https://api.github.com/repos/getsentry/sentry,https://github.com/getsentry/sentry/pull/83085,### Problem\r\n\r\nIf the user is not member o...,Human
4,2332333882,85102,ref(consumers): Rename parallel -> batched-par...,evanpurkhiser,1421724,closed,2025-02-12T21:24:17Z,2025-02-12T22:20:33Z,2025-02-12T22:20:33Z,https://api.github.com/repos/getsentry/sentry,https://github.com/getsentry/sentry/pull/85102,Both crons and uptime consumers have a paralle...,Human
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6613,2278132921,32786,Prototype: Enhance Supabase Studio User Impers...,sandengocka,22433712,closed,2025-01-15T01:52:11Z,2025-01-22T10:00:59Z,2025-01-22T10:00:59Z,https://api.github.com/repos/supabase/supabase,https://github.com/supabase/supabase/pull/32786,## I have read the [CONTRIBUTING.md](https://g...,Human
6614,2363711435,183,Update README_CN.md,chonchoi,7456582,closed,2025-02-28T04:53:17Z,2025-02-28T04:59:45Z,2025-02-28T04:59:45Z,https://api.github.com/repos/PySpur-Dev/pyspur,https://github.com/PySpur-Dev/pyspur/pull/183,"Fix translations that are overly ""AI-like.""\r\...",Human
6615,2284333641,1741,[sidecar] get tool use time taken for each node,theskcd,10356126,closed,2025-01-17T13:30:40Z,2025-01-17T13:30:46Z,2025-01-17T13:30:46Z,https://api.github.com/repos/codestoryai/sidecar,https://github.com/codestoryai/sidecar/pull/1741,None,Human
6616,2503287360,89,perf(copool): remove lock in queue,noneback,46670806,closed,2025-05-07T05:26:42Z,2025-05-07T05:31:00Z,2025-05-07T05:31:00Z,https://api.github.com/repos/noneback/go-taskflow,https://github.com/noneback/go-taskflow/pull/89,None,Human
6617,2566240535,331,improvement: Add separate login / signup screens,brendan-kellam,10233483,closed,2025-06-04T06:21:57Z,2025-06-04T23:42:52Z,2025-06-04T23:42:52Z,https://api.github.com/repos/sourcebot-dev/sou...,https://github.com/sourcebot-dev/sourcebot/pul...,This PR adds a separate signup screen and a sm...,Human

In [ ]:
human_pr_task_type_df

,agent,id,title,reason,type,confidence
0,Human,2438086945,:bug: fix: update how we fetch workflow_id and...,The PR title and description indicate a correc...,fix,NaN
1,Human,2336888723,feat(aci): add automations index page,The title indicates the addition of a new feat...,feat,NaN
2,Human,2564963212,feat(insights): update ux for open in explore ...,The PR introduces updated user experience (UX)...,feat,NaN
3,Human,2474210990,feat(compare): Add timestamp column to sample ...,The PR introduces a new feature by adding a ti...,feat,NaN
4,Human,2486573779,ref(perf-issues): Consolidate File IO override...,The PR improves the performance issue detectio...,perf,NaN
...,...,...,...,...,...,...
6613,Human,2363711435,Update README_CN.md,The changes are focused on improving the trans...,docs,NaN
6614,Human,2470029531,Adding zod validation,The PR introduces a new feature by adding Zod ...,feat,NaN
6615,Human,2284333641,[sidecar] get tool use time taken for each node,The PR introduces a new feature to get tool us...,feat,NaN
6616,Human,2566240535,improvement: Add separate login / signup screens,The PR introduces new features including separ...,feat,NaN
6617,Human,2278132921,Prototype: Enhance Supabase Studio User Impers...,The PR introduces a new feature that extends S...,feat,NaN

# Extract patches for merged Agentic PRs

In [ ]:
merged_pr_mask = ~pr_df['merged_at'].isna()
merged_pr_ids = pr_df[merged_pr_mask]['id']
patch_mask = pr_commit_details_df['pr_id'].isin(merged_pr_ids)
pr_commit_details_df[patch_mask]['patch'].dropna()

0         @@ -0,0 +1,38 @@\n+name: Compile llms.txt\n+\n...
1         @@ -0,0 +1,47 @@\n+import os\n+from pathlib im...
3         @@ -1,47 +1,48 @@\n import os\n from pathlib i...
4         @@ -3,45 +3,60 @@\n \n \n def compile_llms_txt...
6         @@ -1,29 +1,34 @@\n-import os\n from pathlib i...
                                ...
711885    @@ -2,6 +2,7 @@\n \n Servers focused on static...
711918    @@ -0,0 +1,53 @@\n+# numbagg Development Guide...
711919    @@ -49,5 +49,5 @@ uv run pytest numbagg/test/t...
711920    @@ -339,7 +339,7 @@\n                         ...
711921    @@ -1117,7 +1117,7 @@ export interface ModelHi...
Name: patch, Length: 402836, dtype: object

In [ ]:
pr_commit_details_df['is_na'] = pr_commit_details_df['patch'].isna()
merged = pd.merge(pr_commit_details_df, all_pr_df[['id', 'agent']], left_on='pr_id', right_on='id')
merged.groupby('agent').apply(lambda x: x['is_na'].value_counts())

/tmp/ipykernel_280/2143530944.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  merged.groupby('agent').apply(lambda x: x['is_na'].value_counts())

is_na          False  True
agent
Claude_Code    20749   2547
Copilot       154744  32503
Cursor         35162   2676
Devin         152064  17403
OpenAI_Codex  279002  15073

### Check PR type

In [ ]:
pr_task_type_df

,agent,id,title,reason,type,confidence
0,Claude_Code,3264933329,Fix: Wait for all partitions in load_collectio...,title provides conventional commit label,fix,10
1,Claude_Code,3265709660,feat: add comprehensive README screenshots wit...,title provides conventional commit label,feat,10
2,Claude_Code,3265782173,chore: remove HashedPostStateProvider trait,title provides conventional commit label,chore,10
3,Claude_Code,3231949586,feat(swagger): Add Swagger annotations to Batc...,title provides conventional commit label,feat,10
4,Claude_Code,3231950376,feat(swagger): Add Swagger annotations to Batc...,title provides conventional commit label,feat,10
...,...,...,...,...,...,...
33591,Devin,2857168507,Add close button to settings modal,The commit introduces a new feature by adding ...,feat,9
33592,Devin,2858527610,Add Doxygen Documentation for Public APIs,The changes involve adding comprehensive Doxyg...,docs,10
33593,Devin,2858429985,Improve environment variable documentation,The PR focuses on improving and adding documen...,docs,10
33594,Devin,3260345989,Match dividend check pattern to invoice requir...,The change updates the eligibility check logic...,refactor,8
33595,Devin,3275228771,Remove line break tags from homepage to fix re...,The change involves removing <br/> tags to fix...,fix,9

In [ ]:
pr_task_type_df['type'].value_counts()

type
feat        14450
fix          8106
docs         3887
test         2356
refactor     2288
chore         896
build         627
ci            411
perf          340
style         188
other          31
revert         16
Name: count, dtype: int64